name: Send tomorrow's power outage schedule

on:
  schedule:
    # Отправка в 18:00 UTC = 20:00 Киев
    - cron: "0/15 * * * *"
  workflow_dispatch:

jobs:
  tomorrow-schedule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm install
          npx playwright install chromium
          
      - name: Get and send tomorrow's schedule
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REGION: ${{ secrets.REGION }}
          CITY: ${{ secrets.CITY }}
          STREET: ${{ secrets.STREET }}
          HOUSE: ${{ secrets.HOUSE }}
        run: node ./src/tomorrow-schedule.js
